version: '3.3'

services:
  ecos_backend_image:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: ecos_backend
    image: johedotcom/ecos-backend-repository:latest
    restart: always
    ports:
      - '0.0.0.0:4040:3000'
    volumes:
      - .:/usr/src/app
    command: ['node', 'dist/main.js']