version: '3.3'

services:
  ecos_backend_image:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: ecos_backend
    image: johedotcom/ecos-backend-repository:latest
    restart: always
    environment:
      - DATABASE_URL_NETMAN=postgresql://root:Ph@mNgocH4n@10.22.65.209:5432/db_ecos
      - DATABASE_URL=postgresql://root:Ph@mNgocH4n@ecos.joheee.com:5432/db_ecos
      - IMAGE_SERVER_ENDPOINT=http://ecos.joheee.com:4050
    ports:
      - '0.0.0.0:4040:3000'
    volumes:
      - .:/usr/src/app
    command: ['node', 'dist/main.js']